field: 84ec6454-1095-45b4-a86f-4855750af881 # Post Content
fieldLayouts:
  2f3eca88-7a2b-407a-9fbd-39ec9aaec764:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 66045a9e-eefb-492a-9aa1-a9c7d5f0c68c # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a65e10e-0257-4562-b3a9-d5589379cb6d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a3804a34-6371-4266-94bd-c8e4cf0b95e5
        userCondition: null
fields:
  66045a9e-eefb-492a-9aa1-a9c7d5f0c68c: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: true
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:966a7d4b-62d2-4770-be0b-3da984dfbc19' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:966a7d4b-62d2-4770-be0b-3da984dfbc19' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
