field: 886b46bf-da60-4dcc-a940-a7e0854a7403 # Post Content
fieldLayouts:
  f26c581c-0f3d-4533-90d8-6cdc4abeaf09:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: df98fed2-fa22-418c-bb3c-04df4d1e7164 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abef0de7-1f2e-453d-aaf5-2f989fd5d51f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7b198a3a-1edb-4c1d-b6a5-89bd25b7a6cf
        userCondition: null
fields:
  df98fed2-fa22-418c-bb3c-04df4d1e7164: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: true
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:8b2a7c04-48f7-4fb6-8dc5-be277443d4fc' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:8b2a7c04-48f7-4fb6-8dc5-be277443d4fc' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
