field: 84ec6454-1095-45b4-a86f-4855750af881 # Post Content
fieldLayouts:
  14e7f5a0-97b9-40bf-bb81-00ec7cd68962:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: df7f45a8-4b01-4b88-8631-701431b9770e # Quote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8a4745c-3e5d-4c50-b41e-a52717a2be30
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d7a9b577-fe2e-415c-8dd6-7c29f3ebbd6f
        userCondition: null
fields:
  df7f45a8-4b01-4b88-8631-701431b9770e: # Quote
    columnSuffix: iaezrtig
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: null
    name: Quote
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 3
