fieldLayouts:
  0a63275c-aea5-405d-bb7c-84199824add4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 556d8c20-1eae-4943-82e2-afca189cb9dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c9e4a835-d634-4029-8c9d-475e1fe3b26f # Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 842a5239-5489-4740-baf9-0678294ee0ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 135505bb-6683-40d7-8961-76d77c88421e # Profile Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d32ab1cd-5e86-473b-bda2-687f1928ca4f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 420fe634-065c-4eca-8693-2fa26720dbf4
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 6337991d-bfd5-4045-9826-6acfdbd2e759 # About
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
