fieldLayouts:
  e56729d0-4f6c-4058-adfd-d8b6dc018a5d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 85a38ed8-c26d-493d-99b6-9db065040236
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c25ef9e9-79c2-4dc5-ad02-a0e139b2b7b8 # Profile Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8aa71fc7-2c28-4a48-aca6-c0174715c895
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 43916e71-d8c6-401a-89d6-b349372bd1ed # Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99e1a63c-11cc-48c5-8e44-91c62ff9921e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eabc9fc5-ff7b-49d6-b849-3969ab7842ca
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 1b57e832-0969-4f6f-a21d-70154bb6832c # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
