fieldLayouts:
  80a61f69-02c9-437b-99cb-952a42b1f099:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3af18233-7e75-417e-bb57-0607131de732
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1c74848f-584f-49dd-a891-14c358833908 # Profile Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e0063a2-a1ed-4ed4-803d-6381fbc2f5d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 687d3fa9-27f4-494b-9c65-59ba7106c23a # Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d876b0bb-27dc-49f4-b596-d73707a72eb0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 709af229-4729-42d5-9fa0-e3205e7746c0
        userCondition: null
handle: about
hasTitleField: false
name: About
section: 46935009-9fcc-478e-bfa4-a249b778952b # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
