fieldLayouts:
  ef0c96f8-b164-4560-b4c1-96568fdce01b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e8bea627-dcdd-4b4c-b603-66e88f38bc5b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 83b692c6-234d-44e4-9a64-29e912087415 # Topics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fb11369-a152-4bcf-a656-ef96e4c34bd2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ff595ed-a375-408b-9cb8-19c002ff9b87 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f072e2d-bf30-429a-816d-01b26e6f04f1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 84ec6454-1095-45b4-a86f-4855750af881 # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ec59cae-70a5-4458-861d-6e15d61671fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8f2c3fea-0e7d-4e44-b384-ba7a489363d9 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 564bf280-6886-4183-880d-854ab309b8fd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9aa8cba7-6c1b-466c-ba71-e718382cd42a
        userCondition: null
handle: post
hasTitleField: true
name: Post
section: 67c28def-efd1-4922-95a8-93f9522a642f # Blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
