fieldLayouts:
  232bf8ff-cd90-43fd-9ed8-d821e9a556aa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7d14aad9-33c6-4329-9a31-d9b6c9fd6c2b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 92d55be7-555b-440b-b9a8-d2642e7ca5cf # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7f5eb60-cedb-4798-a99a-86f0415878ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fe9323c5-36cd-413c-a595-ee6d7dda65de # Topics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4e5541a-9d98-4a67-998a-6d392d8a761d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bdf483fb-8811-4908-82b5-82c35ce0707e # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 09068abe-f4ec-438b-bf15-76951dc1f07c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 95a4b6b0-053d-43e2-82b1-fb53b30b06af # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd149345-a626-4ad1-8d86-1b799bc9ecc9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c52a3e38-f49a-40ba-b2ed-ea15e8b26133
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9c5b987-d366-434a-b3b7-185b5071af18
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 78a4a692-39e2-48d2-8320-7c6291bc615c
        userCondition: null
handle: post
hasTitleField: true
name: Post
section: abd7299e-407f-41d0-9827-42245f1762fe # Blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
