baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Tutorial Site'
primary: true
siteGroup: fee3d556-a4f3-4e7e-ba19-aa389f5d5d4a # Tutorial Site
sortOrder: 1
