baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Tutorial Site'
primary: true
siteGroup: 7308b14d-cc31-4e86-8652-f9071c0efa6f # Tutorial Site
sortOrder: 1
