columnSuffix: dmbpjgsz
contentColumnType: text
fieldGroup: 1f377646-fc1c-46a6-8aed-e39774201adc # Global
handle: description
instructions: null
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
