columnSuffix: null
contentColumnType: string
fieldGroup: 4dfc25d9-6f06-4a20-acf6-161b0bcac4e4 # Blog
handle: postContent
instructions: null
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
