columnSuffix: null
contentColumnType: string
fieldGroup: 3bb780d9-143a-44f5-93b1-484a288ad88b # Blog
handle: postContent
instructions: null
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
