columnSuffix: null
contentColumnType: string
fieldGroup: 38eef2bd-7d77-4434-b88f-77b1b8ca2eb7 # About
handle: profilePhoto
instructions: null
name: 'Profile Photo'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:8b2a7c04-48f7-4fb6-8dc5-be277443d4fc' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:8b2a7c04-48f7-4fb6-8dc5-be277443d4fc' # Images
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:8b2a7c04-48f7-4fb6-8dc5-be277443d4fc' # Images
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
