columnSuffix: null
contentColumnType: string
fieldGroup: 9a70447f-02cb-470a-badf-d67b1ffab7f3 # Blog
handle: topics
instructions: null
name: Topics
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:8338ab10-7fd0-463f-a018-2a9694047a30' # Topics
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
