columnSuffix: null
contentColumnType: string
fieldGroup: 4dfc25d9-6f06-4a20-acf6-161b0bcac4e4 # Blog
handle: topics
instructions: null
name: Topics
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:6477d700-1ef7-4415-b9c5-e91f7a55b9f2' # Topics
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
