dateModified: 1691445391
email:
  fromEmail: jabal@fivetwofive.com
  fromName: craft-test
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
meta:
  __names__:
    1b57e832-0969-4f6f-a21d-70154bb6832c: About # About
    1c401a2a-0e45-402b-96b0-6e38edb7566e: Text # Text
    1cd6d061-44da-40cb-a1f7-68e1a605c7cd: Post # Post
    1f377646-fc1c-46a6-8aed-e39774201adc: Global # Global
    3cc8ad2d-dab8-43e1-9673-48be60532d16: Text # Text
    9a70447f-02cb-470a-badf-d67b1ffab7f3: Blog # Blog
    9f136435-1320-4313-a74e-f2201e29e183: Common # Common
    63a8f6da-38e7-4141-901a-a4dfd36fd619: Description # Description
    65e47780-9585-4fcf-a8f5-3683e6ec1e2c: Images # Images
    84a80685-2a9b-4cec-8059-a370c7fcf152: About # About
    088c2300-7722-4813-bfe1-5fe194c182a4: Thumbnail # Thumbnail
    90dae052-7e10-495e-b865-7f417f8b9e2f: 'Site Info' # Site Info
    92d55be7-555b-440b-b9a8-d2642e7ca5cf: 'Feature Image' # Feature Image
    94b7bdd1-6568-49a2-991e-64a7ba6c9107: Simple # Simple
    95a4b6b0-053d-43e2-82b1-fb53b30b06af: 'Post Content' # Post Content
    138ddded-e7d3-4a9b-85b1-db7825c1b5a7: Quote # Quote
    379f0d98-b240-4bd4-b868-1e438ab7fdd0: Quote # Quote
    8338ab10-7fd0-463f-a018-2a9694047a30: Topics # Topics
    43916e71-d8c6-401a-89d6-b349372bd1ed: Bio # Bio
    96684751-f7fe-4393-be93-c2a3c78fc587: craft-test # craft-test
    abd7299e-407f-41d0-9827-42245f1762fe: Blog # Blog
    bb8f359f-9038-4d1a-abf1-01bb08b2ddf8: 'Post Content config' # Post Content config
    bdf483fb-8811-4908-82b5-82c35ce0707e: Summary # Summary
    c25ef9e9-79c2-4dc5-ad02-a0e139b2b7b8: 'Profile Photo' # Profile Photo
    cb106b50-ce48-47da-8a25-3b24cee634ce: Image # Image
    d5ebd6fc-9dcf-4c94-a1af-370e1977d753: Image # Image
    eeff00cf-4aab-4e73-b0a8-f75cfb384387: About # About
    fe9323c5-36cd-413c-a595-ee6d7dda65de: Topics # Topics
    ff3f0ade-2d6b-4cc8-ac3e-d5599925b13e: craft-test # craft-test
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: solo
  live: true
  name: craft-test
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
