dateModified: 1691612984
email:
  fromEmail: jtorres@activecampaign.com
  fromName: 'Tutorial Site'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    1c74848f-584f-49dd-a891-14c358833908: 'Profile Photo' # Profile Photo
    3e00c9a2-2a63-4e9c-81c7-82cd588e08e9: 'Tutorial Site' # Tutorial Site
    4dfc25d9-6f06-4a20-acf6-161b0bcac4e4: Blog # Blog
    6ff595ed-a375-408b-9cb8-19c002ff9b87: Summary # Summary
    8da18c8e-1645-4995-b960-7a4b9bad4f20: Image # Image
    8f2c3fea-0e7d-4e44-b384-ba7a489363d9: 'Feature Image' # Feature Image
    37c9ec83-f71d-42e8-99ab-b3c7f95886f3: Text # Text
    52e9a500-b109-407e-b187-4faffbfd3bde: Global # Global
    67c28def-efd1-4922-95a8-93f9522a642f: Blog # Blog
    83b692c6-234d-44e4-9a64-29e912087415: Topics # Topics
    84ec6454-1095-45b4-a86f-4855750af881: 'Post Content' # Post Content
    131d0deb-2e3c-4c1d-94ed-150411ed0370: Post # Post
    687d3fa9-27f4-494b-9c65-59ba7106c23a: Bio # Bio
    966a7d4b-62d2-4770-be0b-3da984dfbc19: Images # Images
    6477d700-1ef7-4415-b9c5-e91f7a55b9f2: Topics # Topics
    7016fe27-f48f-4cfc-a214-303166d3b6dd: Text # Text
    7308b14d-cc31-4e86-8652-f9071c0efa6f: 'Tutorial Site' # Tutorial Site
    50983ca2-aeb5-42d3-b9a6-a0a3dc136af5: About # About
    66045a9e-eefb-492a-9aa1-a9c7d5f0c68c: Image # Image
    46935009-9fcc-478e-bfa4-a249b778952b: About # About
    b56a6e6e-52b7-4f83-9b53-9dcb7d85eae9: About # About
    c0acaccc-3815-4253-af03-c8fec26a1f3f: Description # Description
    c7e90bdd-1d20-4342-8198-ddaccaff7a8d: 'Site Info' # Site Info
    d8d165e1-f753-4ce0-9dba-03789f1acd8c: Thumbnail # Thumbnail
    d33b630a-593c-4040-a5d6-3b45e41d4fc7: Common # Common
    dcb50c67-8752-440a-8350-ddec5769edac: Simple # Simple
    df7f45a8-4b01-4b88-8631-701431b9770e: Quote # Quote
    fcd4d3b6-cd49-4c58-bca8-5188c0c6483e: Quote # Quote
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Tutorial Site'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
