dateModified: 1708208511
email:
  fromEmail: jabaltorres@gmail.com
  fromName: 'Tutorial Site'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
meta:
  __names__:
    0afd5de4-5de3-4dc8-99e7-7a6c9df9ea63: 'Tutorial Site' # Tutorial Site
    0f1d7dfe-0c34-48e4-9078-1edfe1ca6e9b: Common # Common
    0f31503b-cd5c-4116-a3b3-c8fed72e2701: 'Feature Image' # Feature Image
    1ca00a3f-93ce-4ef6-a2d4-32b6a2123198: Button # Button
    1f3df265-ec7c-4b27-b693-2a53c5ff1f1b: 'Text Align' # Text Align
    3bb780d9-143a-44f5-93b1-484a288ad88b: Blog # Blog
    4a89105f-c8aa-44f6-83fb-cd3b88ce4946: Default # Default
    4dfcfdf5-8fe2-42b3-b3f8-4c0b3ba749c1: Post # Post
    6de44d1c-affc-400f-a29c-c4bcd8f761f1: Topics # Topics
    6fbaeec9-494a-4e05-aadc-3beb1822db4c: 'Modular Pages' # Modular Pages
    7a1b82eb-d318-46aa-8e8f-7506b48aee2d: Blog # Blog
    8b2a7c04-48f7-4fb6-8dc5-be277443d4fc: Images # Images
    9c554798-c3a0-4549-a6bf-4156ca9be114: Image # Image
    25daa564-16e1-48dc-82cd-e7574dea8af3: Global # Global
    38eef2bd-7d77-4434-b88f-77b1b8ca2eb7: About # About
    59db6485-6d94-4359-a80b-5b3249f82a49: Topics # Topics
    511a57ef-55b0-4515-b21e-227aef13ab2e: About # About
    650bc1ff-e15b-41be-b69b-a7aedaa8efa7: Text # Text
    00651ecb-b941-4cd7-ab71-e7e5cfd3f23b: 'Text Block' # Text Block
    680dd936-cde7-4118-9031-7dc4bfe77573: Button # Button
    886b46bf-da60-4dcc-a940-a7e0854a7403: 'Post Content' # Post Content
    1972d550-c860-4711-96da-5922ac550c76: 'Reusable Fields' # Reusable Fields
    135505bb-6683-40d7-8961-76d77c88421e: 'Profile Photo' # Profile Photo
    162147f8-0e19-48ba-b875-292508a05162: Heading # Heading
    428644de-73aa-4389-9583-68a8bbf8b95c: Summary # Summary
    6337991d-bfd5-4045-9826-6acfdbd2e759: About # About
    ae5a4a98-dea0-40f5-aead-736cd0f611e2: Neo # Neo
    ba2e78a9-85f7-44b7-b77d-fffa2dd3e3f2: 'Heading Class' # Heading Class
    bb6d488a-cd5d-4aa5-82df-960d7b4df07b: Thumbnail # Thumbnail
    bb457ee9-f0a0-4959-9913-9f4a9a38fba2: Text # Text
    c0337644-61c7-421b-8cfc-b8dd2e6382d4: Simple # Simple
    c2d1af71-2e4d-49b3-881f-ad4cd959615e: 'Site Info' # Site Info
    c9e4a835-d634-4029-8c9d-475e1fe3b26f: Bio # Bio
    d0dc1d46-2569-427c-b30b-e139aab00f7c: 'Button URI' # Button URI
    d50039d7-5e92-49af-8946-1f17bc687cb0: 'Neo Modules' # Neo Modules
    df98fed2-fa22-418c-bb3c-04df4d1e7164: Image # Image
    eb68f344-a25b-40b1-ae47-8d293a5d0646: Text # Text
    ee74eb9a-9192-4609-887b-d65bdd26d660: 'Button Text' # Button Text
    fb684f3f-4ef6-4f56-b69b-4abec53cd789: Description # Description
    fee3d556-a4f3-4e7e-ba19-aa389f5d5d4a: 'Tutorial Site' # Tutorial Site
plugins:
  admin-bar:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: 7G8XG30ML7IF9PMDU0OX9HBA
    schemaVersion: 4.0.0
    settings:
      blockTypeIconPath: '@webroot'
      blockTypeIconSelectMode: sources
      blockTypeIconSources: '*'
      collapseAllBlocks: true
      defaultAlwaysShowGroupDropdowns: true
      enableBlockTypeUserPermissions: true
      enableLazyLoadingNewBlocks: true
      newBlockMenuStyle: classic
      optimiseSearchIndexing: true
system:
  edition: solo
  live: true
  name: 'Tutorial Site'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
