defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  0afd5de4-5de3-4dc8-99e7-7a6c9df9ea63: # Tutorial Site
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
  3e00c9a2-2a63-4e9c-81c7-82cd588e08e9: # Tutorial Site
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
